### ISSUE TITLE
App fails to start

### ISSUE THREAD

**Issue by busywhistling** [d1ceward/plausible_on_dokku#12]
**Describe the bug**

Hi, I don't seem to be able to make this app work. App creation and linking works fine, but I keep getting the following error while trying to git push. I went through some other issues and also tried the proxy commands. Right now my environment is:

```bash
=====> plausible env vars
ADMIN_USER_EMAIL:         email@domain.com
ADMIN_USER_NAME:          username
ADMIN_USER_PWD:           password
BASE_URL:                 https://plausible.domain.com/
CLICKHOUSE_DATABASE_URL:  http://plausible:<redacted>@dokku-clickhouse-plausible:8123/plausible
CLICKHOUSE_URL:           clickhouse://plausible:<redacted>@dokku-clickhouse-plausible:9000/plausible
DATABASE_URL:             postgres://postgres:<redacted>@dokku-postgres-plausible:5432/plausible
DOKKU_APP_TYPE:           dockerfile
DOKKU_DOCKERFILE_PORTS:   5000/tcp
DOKKU_PROXY_PORT:         80
DOKKU_PROXY_PORT_MAP:     http:80:5000
GIT_REV:                  1c55839279858d34b484308b6b79cd54d4a4b353
MAILER_EMAIL:             webmaster@domain.com
SECRET_KEY_BASE:          <redacted>
SMTP_HOST_ADDR:           smtp.server.com
SMTP_HOST_PORT:           587
SMTP_HOST_SSL_ENABLED:    1
SMTP_USER_NAME:           email@server.com
SMTP_USER_PWD:            password
```

<details>
<summary>Error</summary>

```bash
remote:  !     App container failed to start!!
=====> Start of plausible web container output:
       00:28:19.794 [error] Clickhousex.Protocol (#PID<0.2571.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
remote: 2021/09/24 02:28:32 exit status 1
       00:28:19.794 [error] Clickhousex.Protocol (#PID<0.2568.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.794 [error] Clickhousex.Protocol (#PID<0.2567.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.795 [error] Clickhousex.Protocol (#PID<0.2570.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.795 [error] Clickhousex.Protocol (#PID<0.2569.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.799 [error] Clickhousex.Protocol (#PID<0.2574.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.799 [error] Clickhousex.Protocol (#PID<0.2576.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.801 [error] Clickhousex.Protocol (#PID<0.2578.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.812 [error] Clickhousex.Protocol (#PID<0.2581.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:19.815 [error] Clickhousex.Protocol (#PID<0.2583.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 151,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1194\">>,message => <<\"relation \\"salts\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"13\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"DELETE FROM \\"salts\\" AS s0 WHERE (s0.\\"inserted_at\\" < now() - '48 hours'::interval)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,751}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,684}]},{'Elixir.Plausible.Session.Salts','-start_link/1-fun-0-',0,[{file,\"lib/plausible/session/salts.ex\"},{line,8}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{lremote: ]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"}
       Kernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Sessionremote: {#{'__exception__' => true,'__struct__' => 'Elix
remote: 
remote: rash dump is being written to: erl_crash.dump...done
       00:28:25.665 [error] Clickhousex.Protocol (#PID<0.2568.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.666 [error] Clickhousex.Protocol (#PID<0.2571.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.666 [error] Clickhousex.Protocol (#PID<0.2567.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.667 [error] Clickhousex.Protocol (#PID<0.2570.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.667 [error] Clickhousex.Protocol (#PID<0.2569.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.670 [error] Clickhousex.Protocol (#PID<0.2574.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.670 [error] Clickhousex.Protocol (#PID<0.2576.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.671 [error] Clickhousex.Protocol (#PID<0.2578.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.675 [error] Clickhousex.Protocol (#PID<0.2581.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:25.677 [error] Clickhousex.Protocol (#PID<0.2583.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 161,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1194\">>,message => <<\"relation \\"salts\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"13\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"DELETE FROM \\"salts\\" AS s0 WHERE (s0.\\"inserted_at\\" < now() - '48 hours'::interval)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,751}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,684}]},{'Elixir.Plausible.Session.Salts','-start_link/1-fun-0-',0,[{file,\"lib/plausible/session/salts.ex\"},{line,8}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{lremote: ]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"}
       Kernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Sessionremote: {#{'__exception__' => true,'__struct__' => 'Elix
remote: 
remote: rash dump is being written to: erl_crash.dump...done
       00:28:30.797 [error] Clickhousex.Protocol (#PID<0.2568.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.798 [error] Clickhousex.Protocol (#PID<0.2571.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.798 [error] Clickhousex.Protocol (#PID<0.2567.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.799 [error] Clickhousex.Protocol (#PID<0.2570.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.799 [error] Clickhousex.Protocol (#PID<0.2569.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.802 [error] Clickhousex.Protocol (#PID<0.2574.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.802 [error] Clickhousex.Protocol (#PID<0.2576.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.803 [error] Clickhousex.Protocol (#PID<0.2578.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.807 [error] Clickhousex.Protocol (#PID<0.2581.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       00:28:30.809 [error] Clickhousex.Protocol (#PID<0.2583.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 167,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1194\">>,message => <<\"relation \\"salts\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"13\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"DELETE FROM \\"salts\\" AS s0 WHERE (s0.\\"inserted_at\\" < now() - '48 hours'::interval)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,751}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,684}]},{'Elixir.Plausible.Session.Salts','-start_link/1-fun-0-',0,[{file,\"lib/plausible/session/salts.ex\"},{line,8}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{lremote: ]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"}
       Kernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Sessionremote: {#{'__exception__' => true,'__struct__' => 'Elix
remote: 
remote: rash dump is being written to: erl_crash.dump...done
=====> End of plausible web container output
remote: 2021/09/24 02:28:33 exit status 1
remote: 2021/09/24 02:28:33 exit status 1
To domain.com:plausible
 ! [remote rejected] master -> master (pre-receive hook declined)
```

</details>

**Comment by D1ceWard** [comment]
What is the version of clickhouse? and could you give back this error with ` LOG_LEVEL=debug` environment variable enabled ? (`dokku config:set plausible LOG_LEVEL=debug`)

**Comment by busywhistling** [comment]
Hey, thanks for helping. I've added the error with the debug env set.
<details>
<summary>Error</summary>

```bash
remote:  !     App container failed to start!!
=====> Start of plausible web container output:
       10:59:29.082 [info] AppSignal disabled.
       10:59:29.085 [debug] Appsignal.Error.Backend attached to Logger
       10:59:29.089 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :start]
       10:59:29.089 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :stop]
       10:59:29.777 [error] Clickhousex.Protocol (#PID<0.2568.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.777 [error] Clickhousex.Protocol (#PID<0.2571.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.778 [error] Clickhousex.Protocol (#PID<0.2570.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.778 [error] Clickhousex.Protocol (#PID<0.2567.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.778 [error] Clickhousex.Protocol (#PID<0.2569.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.784 [error] Clickhousex.Protocol (#PID<0.2578.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.785 [error] Clickhousex.Protocol (#PID<0.2574.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.785 [error] Clickhousex.Protocol (#PID<0.2576.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.786 [error] Clickhousex.Protocol (#PID<0.2580.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.788 [error] Clickhousex.Protocol (#PID<0.2582.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:29.808 [info] Running PlausibleWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:5000 (http)
       10:59:29.827 [info] Access PlausibleWeb.Endpoint at https://plausible.server.com
       10:59:29.833 [debug] QUERY ERROR source="salts" db=0.0ms queue=2.6ms idle=69.8ms
       DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval) []
       10:59:29.835 [info] Flushing session buffer before shutdown...
       10:59:29.836 [info] Flushing event buffer before shutdown...
       10:59:29.888 [info] Application plausible exited: Plausible.Application.start(:normal, []) returned an error: shutdown: failed to start child: Plausible.Session.Salts
           ** (EXIT) an exception was raised:
               ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "salts" does not exist
           query: DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval)
                   (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
                   (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
                   (plausible 0.0.1) lib/plausible/session/salts.ex:8: anonymous fn/0 in Plausible.Session.Salts.start_link/1
                   (elixir 1.11.3) lib/agent/server.ex:8: Agent.Server.init/1
                   (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
                   (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
                   (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       10:59:29.940 [debug] AppSignal stopping.
       {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 27291,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1194\">>,message => <<\"relation \\"salts\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"13\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"DELETE FROM \\"salts\\" AS s0 WHERE (s0.\\"inserted_at\\" < now() - '48 hours'::interval)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,751}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,684}]},{'Elixir.Plausible.Session.Salts','-start_link/1-fun-0-',0,[{file,\"lib/plausible/session/salts.ex\"},{line,8}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"remote: 
remote: ernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elix
remote: 
remote: rash dump is being written to: erl_crash.dump...done
       10:59:34.441 [info] AppSignal disabled.
       10:59:34.442 [debug] Appsignal.Error.Backend attached to Logger
       10:59:34.443 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :start]
       10:59:34.444 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :stop]
       10:59:35.429 [info] Running PlausibleWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:5000 (http)
       10:59:35.459 [info] Access PlausibleWeb.Endpoint at https://plausible.server.com
       10:59:35.469 [debug] QUERY ERROR source="salts" db=0.0ms queue=1.0ms idle=130.8ms
       DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval) []
       10:59:35.472 [info] Flushing session buffer before shutdown...
       10:59:35.475 [info] Flushing event buffer before shutdown...
       10:59:35.586 [info] Application plausible exited: Plausible.Application.start(:normal, []) returned an error: shutdown: failed to start child: Plausible.Session.Salts
           ** (EXIT) an exception was raised:
               ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "salts" does not exist
           query: DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval)
                   (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
                   (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
                   (plausible 0.0.1) lib/plausible/session/salts.ex:8: anonymous fn/0 in Plausible.Session.Salts.start_link/1
                   (elixir 1.11.3) lib/agent/server.ex:8: Agent.Server.init/1
                   (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
                   (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
                   (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       10:59:35.733 [debug] AppSignal stopping.
remote: 2021/10/03 12:59:42 exit status 1
       {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 27304,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1194\">>,message => <<\"relation \\"salts\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"13\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"DELETE FROM \\"salts\\" AS s0 WHERE (s0.\\"inserted_at\\" < now() - '48 hours'::interval)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,751}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,684}]},{'Elixir.Plausible.Session.Salts','-start_link/1-fun-0-',0,[{file,\"lib/plausible/session/salts.ex\"},{line,8}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"remote: 
remote: ernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elix
remote: 
remote: rash dump is being written to: erl_crash.dump...done
       10:59:40.470 [info] AppSignal disabled.
       10:59:40.470 [debug] Appsignal.Error.Backend attached to Logger
       10:59:40.472 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :start]
       10:59:40.472 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :stop]
       10:59:40.833 [error] Clickhousex.Protocol (#PID<0.2567.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.833 [error] Clickhousex.Protocol (#PID<0.2568.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.834 [error] Clickhousex.Protocol (#PID<0.2570.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.834 [error] Clickhousex.Protocol (#PID<0.2571.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.834 [error] Clickhousex.Protocol (#PID<0.2569.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.837 [error] Clickhousex.Protocol (#PID<0.2574.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.837 [error] Clickhousex.Protocol (#PID<0.2576.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.838 [error] Clickhousex.Protocol (#PID<0.2578.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.841 [error] Clickhousex.Protocol (#PID<0.2580.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.844 [error] Clickhousex.Protocol (#PID<0.2583.0>) failed to connect: ** (ErlangError) Erlang error: :econnrefused
       10:59:40.856 [info] Running PlausibleWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:5000 (http)
       10:59:40.871 [info] Access PlausibleWeb.Endpoint at https://plausible.server.com
       10:59:40.875 [debug] QUERY ERROR source="salts" db=0.0ms queue=1.2ms idle=58.2ms
       DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval) []
       10:59:40.877 [info] Flushing session buffer before shutdown...
       10:59:40.878 [info] Flushing event buffer before shutdown...
       10:59:40.946 [info] Application plausible exited: Plausible.Application.start(:normal, []) returned an error: shutdown: failed to start child: Plausible.Session.Salts
           ** (EXIT) an exception was raised:
               ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "salts" does not exist
           query: DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval)
                   (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
                   (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
                   (plausible 0.0.1) lib/plausible/session/salts.ex:8: anonymous fn/0 in Plausible.Session.Salts.start_link/1
                   (elixir 1.11.3) lib/agent/server.ex:8: Agent.Server.init/1
                   (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
                   (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
                   (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       10:59:40.998 [debug] AppSignal stopping.
       {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 27312,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1194\">>,message => <<\"relation \\"salts\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"13\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"DELETE FROM \\"salts\\" AS s0 WHERE (s0.\\"inserted_at\\" < now() - '48 hours'::interval)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,751}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,684}]},{'Elixir.Plausible.Session.Salts','-start_link/1-fun-0-',0,[{file,\"lib/plausible/session/salts.ex\"},{line,8}]},{'Elixir.Agent.Server',init,1,[{file,\"lib/agent/server.ex\"},{line,8}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"remote: 
remote: ernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.Plausible.Session.Salts',{#{'__exception__' => true,'__struct__' => 'Elix
remote: 
remote: rash dump is being written to: erl_crash.dump...done
=====> End of plausible web container output
remote: 2021/10/03 12:59:43 exit status 1
remote: 2021/10/03 12:59:43 exit status 1
To cloud.server.com:plausible
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'cloud.server.com:plausible'
```

</details>

**Comment by D1ceWard** [comment]
I don't see more information about the error with the debug info.

I think it's related to a bad version of `clickhouse`, `0.7.0` is the version of the dokku plugin, to get the version of `clickhouse` you have to run the command `dokku clickhouse:info plausible` (assuming the app is called plausible) and read the version line `Version:`, it should be `20.8.17.25`.

Ex :
![image](https://user-images.githubusercontent.com/8332823/135755182-19f3827a-6ee8-41f1-887b-6f24a4f8afd5.png)

**Comment by busywhistling** [comment]
Hi, I'm running the latest clickhouse, so `yandex/clickhouse-server:20.8.17.25`.

**Comment by busywhistling** [comment]
The interesting thing is that installation instructions (using `docker-compose`) from the website work fine. I'm too trying to figure out how to package that using dokku.

**Comment by busywhistling** [comment]
Hey, I was able to finally make it work. :)
