### ISSUE TITLE
App container failed to start

### ISSUE THREAD

**Issue by Neamar** [D1ceWard/plausible_on_dokku#2]
Thanks a lot for this project, seems exactly what I'm looking for.

However, I can't deploy: I followed the whole process, but when pushing to dokku, I get an error.

**To Reproduce**
Here is the config I have:

```
ADMIN_USER_EMAIL:         neamar@neamar.fr
ADMIN_USER_NAME:          neamar
ADMIN_USER_PWD:           REDACTED
BASE_URL:                 https://t.neamar.fr
CLICKHOUSE_DATABASE_URL:  http://plausible:c9b6601cd1fd4b69@dokku-clickhouse-plausible:8123/plausible
CLICKHOUSE_URL:           clickhouse://plausible:c9b6601cd1fd4b69@dokku-clickhouse-plausible:9000/plausible
DATABASE_URL:             postgres://postgres:ef34cc68e444ce7aefff9a5b40a35bdb@dokku-postgres-plausible:5432/plausible
DOKKU_APP_TYPE:           dockerfile
DOKKU_DOCKERFILE_PORTS:   8000/tcp
DOKKU_PROXY_PORT:         80
DOKKU_PROXY_PORT_MAP:     http:80:8000 https:443:8000
GIT_REV:                  371778923a0f37172fec59ed71e1e944efdceb09
SECRET_KEY_BASE:          398a6f5c1dbc48c8e90bdc0cad45a71e4a919735edfea1202ecdf118e7a985842c5df28c21c511434ef5505ab3d53a5821ff1ef63eb55195a3b9e2c6070ee
```

I did create  `CLICKHOUSE_DATABASE_URL`, changing the protocol and port (your doc mentioned that user and password should change too, but your example kept the same values).

When pushing:
```
Enumerating objects: 58, done.
Counting objects: 100% (58/58), done.
Delta compression using up to 16 threads
Compressing objects: 100% (34/34), done.
Writing objects: 100% (58/58), 65.73 KiB | 65.73 MiB/s, done.
Total 58 (delta 20), reused 58 (delta 20), pack-reused 0
-----> Cleaning up...
-----> Building plausible from Dockerfile
remote: build context to Docker daemon  44.03kB
Step 1/6 : ARG PLAUSIBLE_VERSION="v1.3.0"
Step 2/6 : FROM plausible/analytics:$PLAUSIBLE_VERSION
 ---> ea787e180e98
Step 3/6 : CMD ["sh", "-c", "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"]
 ---> Using cache
 ---> fcc5dbdc7549
Step 4/6 : LABEL dokku=
 ---> Using cache
 ---> 1844141faf62
Step 5/6 : LABEL org.label-schema.schema-version=1.0
 ---> Using cache
 ---> 05672afe4c04
Step 6/6 : LABEL org.label-schema.vendor=dokku
 ---> Running in 89e0b84f44d9
Removing intermediate container 89e0b84f44d9
 ---> 7bc3665487c5
Successfully built 7bc3665487c5
Successfully tagged dokku/plausible:latest
-----> Releasing plausible...
-----> Deploying plausible...
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
       No release task found, skipping
-----> No Procfile found in app image
-----> DOKKU_SCALE file exists
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
remote:  !     No procfile found
remote: 2021/04/16 00:27:22 exit status 1
-----> Attempting pre-flight checks (web.1)
       Waiting for 10 seconds ...
aa435deebdf0755526490c92e4ba06599ce25286db947fcb8b720b3066b760d2
remote:  !     App container failed to start!!
=====> plausible web container output:
       Loading plausible..
       Starting dependencies..
       Starting repos..
       create Plausible.Repo database if it doesn't exist
       create Plausible.ClickhouseRepo database if it doesn't exist
       22:27:34.051 [error] Clickhousex.Protocol (#PID<0.179.0>) failed to connect: ** (ErlangError) Erlang error: :nxdomain
       22:27:34.051 [error] Clickhousex.Protocol (#PID<0.178.0>) failed to connect: ** (ErlangError) Erlang error: :nxdomain
       22:27:34.053 [error] GenServer #PID<0.201.0> terminating
       ** (UndefinedFunctionError) function :nxdomain.exception/1 is undefined (module :nxdomain is not available)
           :nxdomain.exception([])
           (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
           (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
           (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       Last message: nil
       22:27:34.059 [error] GenServer #PID<0.203.0> terminating
       ** (UndefinedFunctionError) function :nxdomain.exception/1 is undefined (module :nxdomain is not available)
           :nxdomain.exception([])
           (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
           (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
           (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       Last message: nil
       22:27:34.061 [error] GenServer #PID<0.205.0> terminating
       ** (UndefinedFunctionError) function :nxdomain.exception/1 is undefined (module :nxdomain is not available)
           :nxdomain.exception([])
           (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
           (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
           (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       Last message: nil
       22:27:34.065 [error] GenServer #PID<0.207.0> terminating
       ** (UndefinedFunctionError) function :nxdomain.exception/1 is undefined (module :nxdomain is not available)
           :nxdomain.exception([])
           (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
           (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
           (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
       Last message: nil
       ** (MatchError) no match of right hand side value: {:error, "killed"}
           (plausible 0.0.1) lib/plausible_release.ex:48: anonymous fn/2 in Plausible.Release.createdb/0
           (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
           (plausible 0.0.1) lib/plausible_release.ex:47: Plausible.Release.createdb/0
           (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
           (elixir 1.11.3) lib/code.ex:341: Code.eval_string_with_error_handling/3
=====> end plausible web container output
remote: 2021/04/16 00:27:36 exit status 1
remote: 2021/04/16 00:27:36 exit status 1
remote: 2021/04/16 00:27:36 exit status 1
To neamar.fr:plausible
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'neamar.fr:plausible'
```

It feels like the app can't connect to clickhouse (I confirmed that it has been linked to the app however).

Thanks for your help!

**Comment by Neamar** [comment]
EDIT: I must have messed up with the linking. Relinking clickhouse a third time did the trick.

Sorry for the noise!
